easy_admin:
    site_name: 'Systemstatus'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    list:
        max_results: 15
        actions:
            - show
    design:
        brand_color: '#2A3CA2'
        templates:
            label_null: 'easy_admin_overrides/label_null.html.twig'
        menu:
            - { label: 'menu.dashboards' }
            - { label: 'menu.dashboard.reports', icon: 'file-alt', route: 'dashboard', params: { entityType: 'report' } }
            - { label: 'menu.dashboard.systems', icon: 'cogs', route: 'dashboard', params: { entityType: 'system' } }
            - { label: 'menu.sysstatus' }
            - { label: 'menu.list.reports', icon: 'file', route: 'list', params: { entityType: 'report' }, default: true }
            - { label: 'menu.list.systems', icon: 'cog', route: 'list', params: { entityType: 'system' } }
            - { label: 'menu.configuration' }
            - { entity: 'Theme', icon: 'th-large', label: 'menu.themes' }
            - { entity: 'ThemeCategory', icon: 'arrows-v', label: 'menu.theme_category' }
            - { entity: 'Category', icon: 'list', label: 'menu.categories' }
            - { entity: 'Question', icon: 'question', label: 'menu.questions' }
            - { label: 'menu.admin', permission: ['ROLE_ADMIN'] }
            - { entity: 'User', icon: 'user', label: 'menu.users', permission: 'ROLE_ADMIN' }
            - { entity: 'Group', icon: 'users', label: 'menu.groups', permission: 'ROLE_ADMIN' }
            - { label: 'menu.exports', icon: 'file-excel-o', route: 'export_page', permission: ['ROLE_ADMIN', 'ROLE_EXPORT'] }
        assets:
            css:
                - ckeditor_styles.css
                - styles.css
    entities:
        ThemeCategory:
            class: App\Entity\ThemeCategory
            list:
                fields:
                    - { property: 'sort_order', label: 'entity.theme_category.sort_order' }
                    - { property: 'category', label: 'entity.theme_category.category' }
                    - { property: 'theme', label: 'entity.theme_category.theme' }
                sort: ['sortOrder', 'ASC']
                actions: []

        Theme:
            class: App\Entity\Theme
            show:
                fields:
                    - { property: 'id', label: 'entity.theme.id' }
                    - { property: 'name', label: 'entity.theme.name' }
                    - { property: 'themeCategories', label: 'entity.theme.categories' }
                    - { property: 'systemGroups', label: 'entity.theme.system_groups' }
                    - { property: 'reportGroups', label: 'entity.theme.report_groups' }
            list:
                fields:
                    - { property: 'id', label: 'entity.theme.id' }
                    - { property: 'name', label: 'entity.theme.name' }
                    - { property: 'themeCategories', label: 'entity.theme.categories' }
                    - { property: 'systemGroups', label: 'entity.theme.system_groups' }
                    - { property: 'reportGroups', label: 'entity.theme.report_groups' }
                sort: ['id', 'ASC']
            form:
                fields:
                    - { property: 'name', label: 'entity.theme.name' }
                    - { property: 'themeCategories', label: 'entity.theme.categories' }
                    - { property: 'systemGroups', label: 'entity.theme.system_groups', type_options: { by_reference: false} }
                    - { property: 'reportGroups', label: 'entity.theme.report_groups', type_options: { by_reference: false} }

        Category:
            class: App\Entity\Category
            list:
                fields:
                    - { property: 'id', label: 'entity.category.id' }
                    - { property: 'name', label: 'entity.category.name' }
                    - { property: 'questions', label: 'entity.category.questions' }
                sort: ['id', 'ASC']
            form:
                fields:
                    - { property: 'name', label: 'entity.category.name' }

        Question:
            class: App\Entity\Question
            list:
                fields:
                    - { property: 'id', label: 'entity.question.id' }
                    - { property: 'sortOrder', label: 'entity.question.sort_order' }
                    - { property: 'question', label: 'entity.question.question' }
                    - { property: 'answers', label: 'entity.question.answers' }
                    - { property: 'category', label: 'entity.question.category' }
                sort: ['id', 'ASC']
            form:
                fields:
                    - { property: 'sortOrder', label: 'entity.question.sort_order' }
                    - { property: 'question', label: 'entity.question.question' }
                    - { property: 'category', label: 'entity.question.category' }
            show:
                fields:
                    - { property: 'sortOrder' }
                    - { property: 'question' }
                    - { property: 'category' }
                    - { property: 'created_by' }
                    - { property: 'updated_by' }
                    - { property: 'created_at', type: 'datetime' }
                    - { property: 'updated_at', type: 'datetime' }

        Answer:
            class: App\Entity\Answer
            list:
                fields:
                    - { property: 'id', label: 'entity.answer.id' }
                    - { property: 'smiley', label: 'entity.answer.smiley', type: 'text', template: 'easy_admin_overrides/field_smiley.html.twig' }
                    - { property: 'note', label: 'entity.answer.note', type: 'text' }
                sort: ['id', 'ASC']
            form:
                fields:
                    - { property: 'question', label: 'entity.answer.question', type_options: { required: false, disabled: disabled } }
                    - { property: 'smiley', label: 'entity.answer.smiley', type_options: { required: false } }
                    - { property: 'note', label: 'entity.answer.text', type: 'textarea', type_options: { required: false} }

        Report:
            class: App\Entity\Report
            list:
                item_permission: ['ROLE_ADMIN']
                fields:
                    - { property: 'id', label: 'entity.report.id' }
            show:
                fields:
                    - { property: 'sys_title', label: 'entity.report.sys_title', type: 'raw' }
                    - { property: 'sys_internal_id', label: 'entity.report.sys_internal_id', type: 'raw' }
                    - { property: 'edoc_url', label: 'entity.report.edoc_url', type: 'url' }
                    - { property: 'sys_link', label: 'entity.report.sys_link', type: 'file', filename: 'Link til anmeldelse' }
                    - { property: 'name', label: 'entity.report.name' }
                    - { property: 'text', label: 'entity.report.text', type: 'raw' }
                    - { property: 'sys_system_owner', label: 'entity.report.sys_system_owner' }
                    - { property: 'groups', label: 'entity.report.groups' }
                    - { property: 'answerarea', label: 'entity.report.answers', type: 'App\Entity\Answer', template: 'easy_admin_overrides/answers_show.html.twig' }
                    - { property: 'sys_alternative_title', label: 'entity.report.sys_alternative_title', type: 'raw' }
                    - { property: 'sys_updated', label: 'entity.report.sys_updated', type: 'datetime' }
                    - { property: 'sys_owner', label: 'entity.report.sys_owner', type: 'raw' }
                    - { property: 'sys_confidential_information', label: 'entity.report.sys_confidential_information', type: 'boolean' }
                    - { property: 'sys_purpose', label: 'entity.report.sys_purpose', type: 'raw' }
                    - { property: 'sys_classification', label: 'entity.report.sys_classification', type: 'raw' }
                    - { property: 'sys_date_for_revision', label: 'entity.report.sys_date_for_revision', type: 'datetime' }
                    - { property: 'sys_persons', label: 'entity.report.sys_persons', type: 'raw' }
                    - { property: 'sys_information_types', label: 'entity.report.sys_information_types', type: 'raw' }
                    - { property: 'sys_data_sent_to', label: 'entity.report.sys_data_sent_to', type: 'raw' }
                    - { property: 'sys_data_come_from', label: 'entity.report.sys_data_come_from', type: 'raw' }
                    - { property: 'sys_data_location', label: 'entity.report.sys_data_location', type: 'raw' }
                    - { property: 'sys_latest_deletion_date', label: 'entity.report.sys_latest_deletion_date', type: 'raw' }
                    - { property: 'sys_data_worth_saving', label: 'entity.report.sys_data_worth_saving', type: 'raw' }
                    - { property: 'sys_data_processors', label: 'entity.report.sys_data_processors', type: 'raw' }
                    - { property: 'sys_data_processing_agreement', label: 'entity.report.sys_data_processing_agreement', type: 'raw' }
                    - { property: 'sys_data_processing_agreement_link', label: 'entity.report.sys_data_processing_agreement_link', type: 'raw' }
                    - { property: 'sys_auditor_statement', label: 'entity.report.sys_auditor_statement', type: 'raw' }
                    - { property: 'sys_auditor_statement_link', label: 'entity.report.sys_auditor_statement_link', type: 'raw' }
                    - { property: 'sys_data_to_science', label: 'entity.report.sys_data_to_science', type: 'raw' }
                    - { property: 'sys_usage', label: 'entity.report.sys_usage', type: 'raw' }
                    - { property: 'sys_request_for_insight', label: 'entity.report.sys_request_for_insight', type: 'raw' }
                    - { property: 'sys_date_use', label: 'entity.report.sys_date_use', type: 'datetime' }
                    - { property: 'sys_status', label: 'entity.report.sys_status', type: 'raw' }
                    - { property: 'sys_remarks', label: 'entity.report.sys_remarks', type: 'raw' }
                    - { property: 'sys_internal_information', label: 'entity.report.sys_internal_information', type: 'raw' }
                    - { property: 'sys_obligation_to_inform', label: 'entity.report.sys_obligation_to_inform', type: 'raw' }
                    - { property: 'sys_legal_basis', label: 'entity.report.sys_legal_basis', type: 'raw' }
                    - { property: 'sys_consent', label: 'entity.report.sys_consent', type: 'raw' }
                    - { property: 'sys_impact_analysis', label: 'entity.report.sys_impact_analysis', type: 'raw' }
                    - { property: 'sys_impact_analysis_link', label: 'entity.report.sys_impact_analysis_link', type: 'raw' }
                    - { property: 'sys_authorization_procedure', label: 'entity.report.sys_authorization_procedure', type: 'raw' }
                    - { property: 'sys_version', label: 'entity.report.sys_version', type: 'raw' }
            form:
                fields:
                    - { type: 'group', label: 'menu.general', icon: 'cog' }
                    - { property: 'sys_title', label: 'entity.report.sys_title', type: 'text', type_options: { required: false, disabled: true } }
                    - { property: 'text', label: 'entity.report.text', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType', type_options: { required: false, config_name: 'simple_toolbar' } }
                    - { property: 'groups', label: 'entity.report.group', type_options: { required: false }, permission: 'ROLE_ADMIN' }
                    - { property: 'edoc_url', label: 'entity.report.edoc_url', type: 'text', type_options: { required: false } }
        System:
            class: App\Entity\System
            list:
                item_permission: ['ROLE_ADMIN']
                fields:
                    - { property: 'id', label: 'entity.system.id' }
            show:
                fields:
                    - { property: 'name', label: 'entity.system.name' }
                    - { property: 'text', label: 'entity.system.text', type: 'raw' }
                    - { property: 'sys_system_owner', label: 'entity.system.sys_system_owner' }
                    - { property: 'groups', label: 'entity.system.groups' }
                    - { property: 'answerarea', label: 'entity.system.answers', type: 'App\Entity\Answer', template: 'easy_admin_overrides/answers_show.html.twig' }
                    - { property: 'sys_title', label: 'entity.system.sys_title', type: 'raw' }
                    - { property: 'sys_internal_id', label: 'entity.system.sys_id', type: 'text' }
                    - { property: 'edoc_url', label: 'entity.system.edoc_url', type: 'url' }
                    - { property: 'sys_link', label: 'entity.system.sys_id_as_link', type: 'file', filename: 'Link til system' }
                    - { property: 'sys_updated', label: 'entity.system.sys_updated', type: 'datetime' }
                    - { property: 'sys_description', label: 'entity.system.sys_description', type: 'raw' }
                    - { property: 'sys_owner', label: 'entity.system.sys_owner', type: 'raw' }
                    - { property: 'sys_owner_subdepartment', label: 'entity.system.sys_owner_subdepartment', type: 'raw' }
                    - { property: 'sys_emergency_setup', label: 'entity.system.sys_emergency_setup', type: 'raw' }
                    - { property: 'sys_contractor', label: 'entity.system.sys_contractor', type: 'raw' }
                    - { property: 'sys_urgency_rating', label: 'entity.system.sys_urgency_rating', type: 'raw' }
                    - { property: 'sys_number_of_users', label: 'entity.system.sys_number_of_users', type: 'raw' }
                    - { property: 'sys_technical_documentation', label: 'entity.system.sys_technical_documentation', type: 'raw' }
                    - { property: 'sys_external_dependencies', label: 'entity.system.sys_external_dependencies', type: 'raw' }
                    - { property: 'sys_important_information', label: 'entity.system.sys_important_information', type: 'raw' }
                    - { property: 'sys_superuser_organization', label: 'entity.system.sys_superuser_organization', type: 'raw' }
                    - { property: 'sys_itsecurity_category', label: 'entity.system.sys_itsecurity_category', type: 'raw' }
                    - { property: 'sys_link_to_security_review', label: 'entity.system.sys_link_to_security_review', type: 'raw' }
                    - { property: 'sys_link_to_contract', label: 'entity.system.sys_link_to_contract', type: 'raw' }
                    - { property: 'sys_end_of_contract', label: 'entity.system.sys_end_of_contract', type: 'datetime' }
                    - { property: 'sys_status', label: 'entity.system.sys_status', type: 'raw' }
                    - { property: 'sys_open_data', label: 'entity.system.sys_open_data', type: 'raw' }
                    - { property: 'sys_open_source', label: 'entity.system.sys_open_source', type: 'raw' }
                    - { property: 'sys_digital_post', label: 'entity.system.sys_digital_post', type: 'raw' }
                    - { property: 'sys_system_category', label: 'entity.system.sys_system_category', type: 'raw' }
                    - { property: 'sys_digital_transactions_pr_year', label: 'entity.system.sys_digital_transactions_pr_year', type: 'raw' }
                    - { property: 'sys_total_transactions_pr_year', label: 'entity.system.sys_total_transactions_pr_year', type: 'raw' }
                    - { property: 'sys_self_service_url', label: 'entity.system.sys_self_service_url', type: 'raw' }
                    - { property: 'selfServiceAvailableFromItems', label: 'entity.system.selfServiceAvailableFromItems' }
                    - { property: 'sys_alternative_title', label: 'entity.system.sys_alternative_title', type: 'raw' }
                    - { property: 'sys_version', label: 'entity.system.sys_version', type: 'text', type_options: { required: false, disabled: disabled } }
            form:
                fields:
                    - { type: 'group', label: 'menu.general', icon: 'cog' }
                    - { property: 'sys_title', label: 'entity.system.sys_title', type: 'text', type_options: { required: false, disabled: true } }
                    - { property: 'text', label: 'entity.system.text', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType', type_options: { required: false, config_name: 'simple_toolbar' } }
                    - { property: 'groups', label: 'entity.system.group', type_options: { required: false }, permission: 'ROLE_ADMIN' }
                    - { property: 'edoc_url', label: 'entity.system.edoc_url', type: 'text', type_options: { required: false } }
        User:
            class: App\Entity\User
            list:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - roles
            show:
                fields:
                    - username
                    - email
                    - groups
                    - enabled
                    - lastLogin
                    - roles
            form:
                role: ROLE_ADMIN
                fields:
                    - username
                    - email
                    - groups
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_EXPORT': 'ROLE_EXPORT', 'ROLE_GROUP_ADMIN': 'ROLE_GROUP_ADMIN', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
        Group:
            class: App\Entity\Group
            list:
                fields:
                    - name
                    - reports
                    - systems
            form:
                fields:
                    - name
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
